import doctest

import wal_e.exception

doctest.testmod(wal_e.exception)
